import { Mission, Badge, GalleryItem, Poll, Profile, TwibbonFrame, QuizQuestion } from './types';

export const MOCK_PROFILE: Profile = {
  id: 'user-001',
  full_name: 'Bagas Kencana',
  instansi: 'Sekretariat Negara / Garuda Muda',
  phone: '081234567890',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  role: 'participant',
  group_name: 'Tim Merah-Putih I',
  total_points: 350,
  onboarding_completed: true,
  rank: 4,
};

export const MOCK_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q-1',
    question: 'Di kota manakah naskah Proklamasi Kemerdekaan Indonesia dibacakan oleh Ir. Soekarno pada 17 Agustus 1945?',
    options: [
      'Jalan Pegangsaan Timur No. 56, Jakarta',
      'Gedung Pancasila, Jakarta',
      'Rumah Laksamana Maeda, Jakarta',
      'Tugu Muda, Semarang'
    ],
    correct_answer_index: 0,
    explanation: 'Naskah Proklamasi dibacakan di kediaman Ir. Soekarno di Jalan Pegangsaan Timur No. 56, Jakarta Pusat.',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'q-2',
    question: 'Siapakah tokoh yang merumuskan dan mengetik naskah Proklamasi Kemerdekaan Indonesia dengan mesin ketik?',
    options: [
      'Mohammad Hatta',
      'Sayuti Melik',
      'Achmad Soebardjo',
      'Sukarni'
    ],
    correct_answer_index: 1,
    explanation: 'Sayuti Melik adalah tokoh pemuda yang mengetik naskah asli Proklamasi yang telah disetujui.',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'q-3',
    question: 'Siapakah ibu negara yang menjahit bendera pusaka Sang Saka Merah Putih pertama kali?',
    options: [
      'Ibu Kartini',
      'Ibu Cut Nyak Dien',
      'Ibu Fatmawati',
      'Ibu Dewi Sartika'
    ],
    correct_answer_index: 2,
    explanation: 'Ibu Fatmawati Soekarno menjahit bendera Sang Saka Merah Putih dari dua helai kain merah dan putih.',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'q-4',
    question: 'Peristiwa diculiknya Soekarno dan Hatta oleh para pemuda ke luar kota sebelum Proklamasi dikenal dengan peristiwa...',
    options: [
      'Peristiwa Bandung Lautan Api',
      'Peristiwa Rengasdengklok',
      'Peristiwa 10 November',
      'Peristiwa Ambarawa'
    ],
    correct_answer_index: 1,
    explanation: 'Peristiwa Rengasdengklok terjadi pada 16 Agustus 1945 untuk mendesak penyegeraan Proklamasi Kemerdekaan.',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'q-5',
    question: 'Siapakah pencipta lagu kebangsaan "Indonesia Raya" yang pertama kali diperdengarkan pada Sumpah Pemuda 1928?',
    options: [
      'Ismail Marzuki',
      'W.R. Soepratman',
      'C. Simanjuntak',
      'H. Mutahar'
    ],
    correct_answer_index: 1,
    explanation: 'Wage Rudolf Soepratman menciptakan dan memainkan lagu Indonesia Raya menggunakan biola.',
    order_index: 5,
    is_active: true,
  },
];

export const MOCK_TWIBBON_FRAMES: TwibbonFrame[] = [
  {
    id: 'f-1',
    name: 'Garuda Emas 81',
    accent_color: '#F59E0B',
    title: 'HUT RI KE-81',
    subtitle: 'Nusantara Baru, Indonesia Maju',
    is_active: true,
    order_index: 1,
  },
  {
    id: 'f-2',
    name: 'Merah Putih Patriot',
    accent_color: '#D9272D',
    title: 'GELORA MERDEKA',
    subtitle: '17 AGUSTUS 2026',
    is_active: true,
    order_index: 2,
  },
  {
    id: 'f-3',
    name: 'Kemerdekaan Modern',
    accent_color: '#10B981',
    title: 'INDONESIA 81',
    subtitle: 'Jiwa Raga Untuk Negeri',
    is_active: true,
    order_index: 3,
  },
];

export const MOCK_MISSIONS: Mission[] = [
  {
    id: 'm-01',
    slug: 'selfie-patriotik',
    title: 'Selfie Patriotik 17-an',
    description: 'Ambil foto selfie terbaikmu dengan busana adat / pakaian tema Merah Putih!',
    type: 'checkin',
    points_reward: 100,
    icon_name: 'Camera',
    is_active: true,
    order_index: 1,
  },
  {
    id: 'm-02',
    slug: 'titik-panggung-utama',
    title: 'Jelajah QR: Panggung Utama',
    description: 'Temukan dan scan QR Code di area Panggung Utama Perayaan HUT RI ke-81.',
    type: 'qr_hunt',
    points_reward: 75,
    icon_name: 'QrCode',
    is_active: true,
    order_index: 2,
    location_name: 'Zona A - Panggung Utama',
    coordinates: { lat: -6.175392, lng: 106.827153 },
    radius_meters: 50,
  },
  {
    id: 'm-03',
    slug: 'titik-bazar-umkm',
    title: 'Jelajah QR: Bazar Kuliner Nusantara',
    description: 'Temukan banner QR Code di booth Bazar UMKM Kemerdekaan.',
    type: 'qr_hunt',
    points_reward: 75,
    icon_name: 'MapPin',
    is_active: true,
    order_index: 3,
    location_name: 'Zona B - Lapangan Bazar UMKM',
    coordinates: { lat: -6.175850, lng: 106.827900 },
    radius_meters: 50,
  },
  {
    id: 'm-04',
    slug: 'quiz-kemerdekaan',
    title: 'Kuis Trivia Kemerdekaan RI',
    description: 'Uji pengetahuan sejarah seputar Kemerdekaan Indonesia ke-81 (5 Soal).',
    type: 'quiz',
    points_reward: 100,
    icon_name: 'HelpCircle',
    is_active: true,
    order_index: 4,
  },
  {
    id: 'm-05',
    slug: 'video-gelora-merdeka',
    title: 'Video Pekik "Merdeka!"',
    description: 'Rekam video singkat (maks 15 detik) menyuarakan pesan Kemerdekaan 81.',
    type: 'video',
    points_reward: 125,
    icon_name: 'Video',
    is_active: true,
    order_index: 5,
  },
];

export const MOCK_BADGES: Badge[] = [
  {
    id: 'b-01',
    code: 'pahlawan_tercepat',
    name: 'Pahlawan Tercepat',
    description: 'Diberikan kepada 10 peserta pertama yang melakukan check-in perayaan.',
    icon: '⚡',
    rarity: 'legendary',
  },
  {
    id: 'b-02',
    code: 'raja_trivia',
    name: 'Raja Trivia Sejarah',
    description: 'Menjawab 100% benar pada Kuis Kemerdekaan tanpa salah.',
    icon: '👑',
    rarity: 'rare',
  },
  {
    id: 'b-03',
    code: 'penjelajah_nusantara',
    name: 'Penjelajah Nusantara',
    description: 'Berhasil memindai seluruh titik lokasi QR Hunt di lokasi acara.',
    icon: '🧭',
    rarity: 'rare',
  },
  {
    id: 'b-04',
    code: 'fotografer_patriot',
    name: 'Fotografer Patriot',
    description: 'Mengunggah 3+ foto keseruan 17-an di Wall of Merdeka.',
    icon: '📸',
    rarity: 'common',
  },
];

export const MOCK_GALLERY: GalleryItem[] = [
  {
    id: 'g-1',
    user_id: 'u-101',
    user_name: 'Siti Rahmawati',
    user_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    instansi: 'Komunitas Kebaya Merah',
    type: 'photo',
    image_url: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&q=80&w=800',
    caption: 'Semangat Kemerdekaan ke-81! Kebaya Merah Putih menyatu dengan alam Indonesia 🇮🇩✨ #Merdeka81',
    like_count: 42,
    is_liked: true,
    status: 'approved',
    report_count: 0,
    created_at: '10 menit lalu',
  },
  {
    id: 'g-2',
    user_id: 'u-102',
    user_name: 'Ahmad Fauzi',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    instansi: 'Taruna Pemuda Kemerdekaan',
    type: 'photo',
    image_url: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&q=80&w=800',
    caption: 'Pengibaran Sang Saka Merah Putih di Panggung Utama HUT RI 81. Merdeka! 🔥',
    like_count: 89,
    is_liked: false,
    status: 'approved',
    report_count: 0,
    created_at: '25 menit lalu',
  },
  {
    id: 'g-3',
    user_id: 'u-103',
    user_name: 'Dewi Lestari',
    user_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    instansi: 'Paduan Suara Nusantara',
    type: 'photo',
    image_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800',
    caption: 'Gelora lagu Indonesia Raya bergema merdu. Dirgahayu Republik Indonesia! 🇮🇩❤️',
    like_count: 67,
    is_liked: true,
    status: 'approved',
    report_count: 0,
    created_at: '45 menit lalu',
  },
];

export const MOCK_LEADERBOARD: Profile[] = [
  {
    id: 'l-1',
    full_name: 'Rahmat Hidayat',
    instansi: 'Ikatan Pemuda Nusantara',
    phone: '0812***',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    role: 'participant',
    group_name: 'Tim Merah-Putih I',
    total_points: 520,
    onboarding_completed: true,
    rank: 1,
  },
  {
    id: 'l-2',
    full_name: 'Nadia Pratama',
    instansi: 'Garuda Nusantara',
    phone: '0813***',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    role: 'participant',
    group_name: 'Tim Garuda Emas',
    total_points: 480,
    onboarding_completed: true,
    rank: 2,
  },
  {
    id: 'l-3',
    full_name: 'Deni Kurniawan',
    instansi: 'Sekretariat Panitia 17-an',
    phone: '0815***',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    role: 'participant',
    group_name: 'Tim Merah-Putih I',
    total_points: 420,
    onboarding_completed: true,
    rank: 3,
  },
  MOCK_PROFILE,
  {
    id: 'l-5',
    full_name: 'Maya Indah',
    instansi: 'Komunitas Seni Nusantara',
    phone: '0817***',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    role: 'participant',
    group_name: 'Tim Garuda Emas',
    total_points: 310,
    onboarding_completed: true,
    rank: 5,
  },
];

export const MOCK_POLL: Poll = {
  id: 'poll-01',
  question: 'Pertunjukan Seni Budaya mana yang paling memukau di HUT RI ke-81?',
  options: [
    { id: 'opt-1', label: 'Tari Colossal Nusantara', votes: 142 },
    { id: 'opt-2', label: 'Atraksi Marching Band Garuda', votes: 198 },
    { id: 'opt-3', label: 'Drama Kolosal Perjuangan 1945', votes: 115 },
    { id: 'opt-4', label: 'Konser Musik Kemerdekaan', votes: 87 },
  ],
  is_active: true,
  total_votes: 542,
};
